version: '3.8'

services:
    api:
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production

    db:
        restart: always

    proxy:
        restart: always
        ports:
            - "80:80"
            - "443:443"
